# This is a basic workflow to help you get started with Actions

name: cron-powershell

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: "*/5 * * * *" 

  workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        shell: powershell
        run: |
          ./crontest.ps1
